from utils.error import RestError